### ISSUE TITLE
Compilation fails on macOS.

### ISSUE THREAD

**Issue by rperrot** [AdaCore/gnat-llvm#10]
Hi, 

I wanted to test the code but it fails to compile with the following error : 

```
gnatllvm-arrays.ads:226:27: "Is_Single_Aggregate" is undefined

   compilation of gnatllvm-compile.adb failed

gprbuild: *** compilation phase failed
```

I followed the instruction on the main page. 
(note: macOS 10.14.6, GNAT Community 2019, clang-10 (from macports) )

**Comment by ArnaudCharlet** [comment]
Right, this recent change requires a corresponding change in gnat_src, which will be done a bit later.
In the mean time, you can revert to revision 5db6ab8f60e which doesn't need this gnat change.

**Comment by rperrot** [comment]
Ok thanks for your quick answer !

**Comment by ArnaudCharlet** [comment]
By the way, the needed GNAT change has now been merged in gcc.gnu.org.
