### ISSUE TITLE
Build on master branch fails - no GPR project file

### ISSUE THREAD

**Issue by klnelson** [AdaCore/gnat-llvm#12]
I am unable to build the current master branch on `macOS`.  It fails because the GPR project file for building `gnat-llvm/llvm-interface/lib/rts-native` does not exist, see below.  I do not see any GPR project files for the native RTS in the repository nor anyway for `make setup-rts` to generate one. 

The failure:
```
rm -f a-numaux.adb.orig
PATH=/Users/ken/Projects/gnat/gnat-llvm/llvm-interface/bin:/Users/ken/Projects/gnat/2020/bin/../libexec/gcc/x86_64-apple-darwin17.7.0/8.4.1:$PATH \
        gprbuild -v -n -p --target=llvm -j0 -P/Users/ken/Projects/gnat/gnat-llvm/llvm-interface/lib/rts-native/adainclude/libada \
          -XCFLAGS="-O2 -g" \
          -XEXTRALIBFLAGS=" -gdwarf-aranges" \
          -XLIBRARY_KIND=static
gprbuild: project file "/Users/ken/Projects/gnat/gnat-llvm/llvm-interface/lib/rts-native/adainclude/libada" not found in .:
make[2]: *** [quicklib] Error 4
make[1]: *** [gnatlib-automated] Error 2
make: *** [all] Error 2
```

Host system detail:
```
$ uname -mprsv
Darwin 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64 i386
```

**Comment by ArnaudCharlet** [comment]
Hi Ken,
The latest GNAT LLVM sources depend on recent GNAT sources, so you need to update your sources under the llvm-interface/gcc directory (gnat_src points to gcc/gcc/ada). libada.gpr can be found under gnat_src/libgnat when your GNAT sources are sufficiently recent.
