### ISSUE TITLE
make step fails

### ISSUE THREAD

**Issue by nandub** [AdaCore/gnat-llvm#13]
The `make llvm` step worked as per the README.

However, when performing the `make` step it fails with [here](https://gist.github.com/nandub/4b0613dc9b936afef31ec8ecd759d0a2)

Mac OS High Sierra 10.13.6 (17G13035)
Using GCC 9.1.0 from [here](https://sourceforge.net/projects/gnuada/)
LLVM and Clang 10.0.0 from Homebrew

**Comment by ArnaudCharlet** [comment]
If you are using llvm and clang from brew then you should not perform 'make llvm', so you should simply remove your llvm build and instead follow this part of the README:
<<
  The recommended way to build GNAT LLVM is to use an existing LLVM and clang
  10.0.0 package install via e.g.  "brew install llvm" on Mac OS or
  "sudo apt-get install llvm-dev" on Ubuntu. You can also build llvm yourself
  with the options that suit your needs. After installing/building, make sure
  the llvm bin directory containing llvm-config and clang is in your PATH.
>>
and then go to the "make" step directly.

**Comment by nandub** [comment]
Oh I see, I guess I didn't read carefully the instructions.  I'll try that and see.

**Comment by nandub** [comment]
That work like a charm.  Thanks.

**Comment by ArnaudCharlet** [comment]
Great, thanks for confirming!
