### ISSUE TITLE
"Has_Compatible_Representation" is undefined

### ISSUE THREAD

**Issue by matthewbdwyer** [AdaCore/gnat-llvm#15]
Trying to build gnat-llvm on Ubuntu 20.04 using gcc (GCC) 9.3.1 20200430 (for GNAT Community 2020 20200429).  
Using clang/llvm resulting from "apt install llvm-dev" which resulted in:

mbd$ llvm-config --version
10.0.0
mbd$ clang --version
clang version 10.0.0-4ubuntu1 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

Followed the instructions and the build ended with the following:

gnatllvm-aliasing.adb:303:18: "Has_Compatible_Representation" is undefined (more references follow)

   compilation of gnatllvm-aliasing.adb failed

gprbuild: *** compilation phase failed

FWIW: I built gnat-llvm successfully on Ubuntu 18.04 back in early May.

**Comment by ArnaudCharlet** [comment]
Indeed, the corresponding change in GNAT will be there shortly. In the meantime, you can get back to commit 20ba5ac3e29ec4b5cd3fb4e70f0c67f7f63336bb to get a working build.

**Comment by ArnaudCharlet** [comment]
Change is now committed in gcc.gnu.org
