### ISSUE TITLE
Make fail in Linux host

### ISSUE THREAD

**Issue by emgaspar** [AdaCore/gnat-llvm#18]
Hi,

I have tried to build the toolchain following `README.md` steps but `make` step fails in first stage.

Error message displays the following information:
+ `gen_il*.ad?`: Not found
+ `gnatmake: "gen_il-main.adb" not found`

`gnat-llvm` and `gcc` source are updated to HEAD. I have checked `gnat_src` folder and these files are not located on it.

Building environment:
+ Linux Mint 20.1 
+ CLang 11.0.0
+ GNAT CE 2020
+ `llvm-dev` package installed

Is there any additional step to performance before `make`?

Thanks in advanced.

**Comment by ArnaudCharlet** [comment]
As GNAT LLVM is still in heavy evolution and we're internally using GNAT sources private to AdaCore, there are sometimes discrepancies with the GNAT sources at gcc.gnu.org. To get a successful build of GNAT LVM you'll need for now to use:
- gcc commit acf190b208ae6883e94b (see PR #16)
- GNAT LLVM commit d447ac30d4c3e31d914f7b

**Comment by ArnaudCharlet** [comment]
For your information, the latest GCC master sources should now be usable again.
You still need to use the GNAT LLVM commit d447ac3 for now.

**Comment by Lucretia** [comment]
It'd make more sense if you created a tag, like gcc_10.2.0, rather having to git a commit hash.
