### ISSUE TITLE
Consistent commits between GCC & gnat-llvm?

### ISSUE THREAD

**Issue by simonjwright** [AdaCore/gnat-llvm#19]
(Building on macOS Catalina - probably not relevant?)

I have GCC at commit gcc-mirror/gcc@6606b85 of 4 Feb 2021, & LLVM downloaded from llvm.org at 11.0.0 (they haven’t made an 11.0.1 binary release).

With that GCC commit, I get missing files:
```
cp: /Volumes/Miscellaneous2/ll/gnat-llvm/llvm-interface/gnat_src/libgnat/a-stteou__bootstrap.ads: No such file or directory
gnatmake: "gen_il-main.adb" not found
```
The `gen_il*` files were introduced here at bb19c89. I went back to the parent, d447ac3; now I get 
```
gnatllvm-environment.ads:137:31: "Dynamic_SO_Ref" is undefined (more references follow)
gnatllvm-types.ads:694:31: "SO_Ref" is undefined
gnatllvm-types.ads:695:13: "Is_Static_SO_Ref" is undefined
```
Hmm, the `SO_Ref` lines are 2 years old!

Could you suggest a possible consistent set of commits?

**Comment by ArnaudCharlet** [comment]
Yes, see PR #18

**Comment by simonjwright** [comment]
Great, thanks

**Comment by ArnaudCharlet** [comment]
For your information, the latest GCC master sources should now be usable again.
You still need to use the GNAT LLVM commit d447ac3 for now.
