### ISSUE TITLE
Build fail in a-cfdlli.adb

### ISSUE THREAD

**Issue by simonjwright** [AdaCore/gnat-llvm#3]
Working with commit 190cfeb, LLVM 9.0.0, macOS Mojave, GNAT CE 2019 I get
```
/Volumes/Miscellaneous/ll/gnat-llvm/llvm-interface/bin/llvm-gcc -c -O2 -g -gnatpg -nostdinc -I../adainclude  ../adainclude/a-cfdlli.adb

raised SEM_CH5.ANALYZE_LOOP_STATEMENT.SKIP_ANALYSIS : sem_ch5.adb:3694
make[3]: *** [a-cfdlli.o] Error 1
make[2]: *** [quicklib] Error 2
make[1]: *** [gnatlib-automated] Error 2
make: *** [all] Error 2
```

(same error with both the GNAT CE 2019 and the GCC 9.1.0 sources).

**Comment by ArnaudCharlet** [comment]
This error message means you are not using the proper GNAT sources.
As per the README.md, you need more recent GNAT sources from GCC trunk:
svn co svn://gcc.gnu.org/svn/gcc/trunk/gcc/ada llvm-interface/gnat_src

**Comment by simonjwright** [comment]
All looking good now! (I already had a git checkout from git://gcc.gnu.org/git/gcc.git, which I tried first; OK.)

**Comment by ArnaudCharlet** [comment]
Great, thanks for confirming!
