### ISSUE TITLE
[Documentation] Ada on JVM

### ISSUE THREAD

**Issue by ShalokShalom** [AdaCore/gnat-llvm#30]
Just as a heads up: Job opportunities and adoption rate could grow, when more people become aware about GraalVM.

This is a rewrite of the JVM, done by Oracle labs itself.

They created a framework, that allows for the easy integration of new languages with high performance execution, while being still polyglot and fully compatible with existing code.

Both, running on the VM and the creation of native images is possible.

There exists a LLVM implementation, next to a couple of other ones like Ruby, Python and R, and of course the usual JVM languages.

This new framework is called Truffle, the LLVM implementation Sulong.

This means, the fluent integration of Ada in existing Rust, Java or NodeJS environments is possible.

I assume, this is sensible to be integrated into our documentation.

https://www.ssw.uni-linz.ac.at/General/Staff/ManuelRigger/ICOOOLPS16.pdf

**Comment by ArnaudCharlet** [comment]
Thanks for the note, it should definitely be possible to plug GNAT LLVM with Truffle, if someone wants to experiment and report back results here that would be great!

**Comment by ShalokShalom** [comment]
I am more talking about a documentation issue, as this not mentioned currently. 
Do you think its worthy?

**Comment by ArnaudCharlet** [comment]
I think it would make more sense once someone has actually made it work and can explain how to make it work, but if you want to suggest a change already, do not hesitate!

**Comment by ShalokShalom** [comment]
I am sadly no Ada programmer, just interested in the language and exactly the adoption rate is what concerns me. :)
