### ISSUE TITLE
Readme soft link is incorrect

### ISSUE THREAD

**Issue by tj800x** [AdaCore/gnat-llvm#34]
In the readme the soft link command appears to be incorrect.  

Instead of:
`$ ln -s gcc/gcc/ada llvm-interface/gnat_src
`

It should be:
`$ ln -s llvm-interface/gcc/gcc/ada llvm-interface/gnat_src
`

**Comment by ArnaudCharlet** [comment]
Thank you for your report. The instructions are actually correct to create the soft link since the soft link is created under llvm-interface, and therefore relative to llvm-interface already where gcc/gcc/ada is.
