### ISSUE TITLE
Issues while compiling

### ISSUE THREAD

**Issue by GuillermoHazebrouck** [AdaCore/gnat-llvm#37]
I found some issues while compiling with LLVM 15 installed on my Debian:

-  The llvm commands like llvm-config, opt and llvm-dis were not found because they were only present with the version suffix "-15". Using "update-alternatives" was necessary to solve this. Maybe this is something to remind in the instructions?
- The compilation is interrupted for several packages (errout.adb and maybe others) due to warnings and the presence of the -gnatg switch. I had to remove it in order to move forwards and then restore it to compile a certain "System" descendant package. I don't see a way around this (other than resolving the warnings).
- After the gnat llvm bin tools are created, the compilation of the ada library fails because gpr seems to be looking for version 14 of llvm-gcc:

```
PATH=/home/guillermo/Toolchains/adawebpack/gnat-llvm/llvm-interface/bin:$PATH \
gprbuild -v -n -p --target=llvm -j0 -P/home/guillermo/Toolchains/adawebpack/gnat-llvm/llvm-interface/lib/rts-native/adainclude/libada \
  -XCFLAGS="-O2 -g" \
  -XEXTRALIBFLAGS=" -gdwarf-aranges" \
  -XLIBRARY_KIND=static
object directory "/home/guillermo/Toolchains/adawebpack/gnat-llvm/llvm-interface/lib/rts-native/adainclude/../obj-static" created for project Libgnarl
Changing to object directory of "Libgnarl": "/home/guillermo/Toolchains/adawebpack/gnat-llvm/llvm-interface/lib/rts-native/obj-static/"
/usr/bin/clang -c -x c -O2 -g -I../include -DIN_RTS=1 -fexceptions -DSTANDALONE -gdwarf-aranges -I/home/guillermo/Toolchains/adawebpack/gnat-llvm/llvm-interface/lib/rts-native/adainclude /home/guillermo/Toolchains/adawebpack/gnat-llvm/llvm-interface/lib/rts-native/adainclude/thread.c

==============Messages for file: /home/guillermo/Toolchains/adawebpack/gnat-llvm/llvm-interface/lib/rts-native/adainclude/libgnarl.gpr
     3. library project Libgnarl is
                        |
        >>> unable to locate "/home/guillermo/Toolchains/adawebpack/gnat-llvm/llvm-interface/bin/llvm-gcc-14"
gprbuild: *** compilation phase failed
make[2]: *** [Makefile:251: quicklib] Error 7
make[2]: Leaving directory '/home/guillermo/Toolchains/adawebpack/gnat-llvm/llvm-interface'
make[1]: *** [Makefile:222: gnatlib-automated] Error 2
make[1]: Leaving directory '/home/guillermo/Toolchains/adawebpack/gnat-llvm/llvm-interface'
make: *** [Makefile:2: all] Error 2

```
llvm-interface/bin/llvm-gcc-14 does not exist indeed, but the fresh llvm-gcc does. Why is gprbuild looking for that specific version? I suspect this is related the the gprbuild knowledge base...?

**Comment by ArnaudCharlet** [comment]
Thank you for the report.
Current GNAT LLVM requires LLVM version 16 as per the README, so you are trying a combination which is no longer supported. In addition, GNAT LLVM doesn't support alternative names (suffixes) for llvm tools, so you will probably need to rebuild LLVM yourself if you can't find a LLVM 16 package which works out of the box.

**Comment by GuillermoHazebrouck** [comment]
I tried building LLVM myself, but unfortunately my machine runs out of memory in the process and my OS crashes. I'll try to install the LLVM-16 packages then.
And what about the last issue? I still dot see why version 14 of gnat-llvm is requested.

**Comment by ArnaudCharlet** [comment]
The last issue is linked to the non default name of the tools most likely.
