### ISSUE TITLE
Linking on macOS

### ISSUE THREAD

**Issue by simonjwright** [AdaCore/gnat-llvm#4]
Running a test build on macOS mojave failed as follows (`problem.adb` is a file I had lying around, nothing to do with this issue):
```
$ llvm-gnatmake problem
llvm-gcc -c problem.adb
llvm-gnatbind -x problem.ali
llvm-gnatlink problem.ali
clang-10: error: unsupported option '-static-libgcc'
llvm-gnatlink: error when calling /Volumes/Miscellaneous/ll/gnat-llvm/llvm-interface/bin/llvm-gcc
llvm-gnatmake: *** link failed.
$
```

This is a workround:
```
$ llvm-gnatmake problem -largs -shared-libgcc
llvm-gnatbind -x problem.ali
llvm-gnatlink problem.ali -shared-libgcc
$
```

**Comment by ArnaudCharlet** [comment]
Right, and the preferred build mechanism is via gprbuild --target=llvm.
Can you check whether gprbuild --target=llvm works out of the box?

**Comment by simonjwright** [comment]
On 9 Oct 2019, at 17:07, Arnaud Charlet <notifications@github.com> wrote:

> Right, and the preferred build mechanism is via gprbuild --target=llvm.
> Can you check whether gprbuild --target=llvm works out of the box?
> 
Yes.

```
$ gprbuild --target=llvm problem.gpr
Compile
   [Ada]          problem.adb
Bind
   [gprbind]      problem.bexch
   [Ada]          problem.ali
Link
   [link]         problem.adb
```

**Comment by ArnaudCharlet** [comment]
OK, things should work now also with gnatmake after my change, can you confirm?

**Comment by ArnaudCharlet** [comment]
Ah yes, for some reason this didn't cause troubles on linux. Fix on its way.

**Comment by simonjwright** [comment]
Yes! (and llvm-gnatmake worked without any extra flags.)

**Comment by ArnaudCharlet** [comment]
Good!
