### ISSUE TITLE
Cross-compilation toolchain

### ISSUE THREAD

**Issue by anonymix007** [AdaCore/gnat-llvm#45]
There are a few different issues here:
1. target_* flags are parsed incorrectly. They assume no cross-compilation. The following patch seems to fix it:
```patch
From 75323602367d6741475457ca256deb228ed53714 Mon Sep 17 00:00:00 2001
From: anonymix007 <48598263+anonymix007@users.noreply.github.com>
Date: Wed, 27 Mar 2024 17:21:38 +0300
Subject: [PATCH] Fix target detection

---
 llvm-interface/Makefile | 5 ++++-
 1 file changed, 4 insertions(+), 1 deletion(-)

diff --git a/llvm-interface/Makefile b/llvm-interface/Makefile
index 7877c0d9..c5829057 100644
--- a/llvm-interface/Makefile
+++ b/llvm-interface/Makefile
@@ -175,7 +175,7 @@ clean:
 
 # Full runtime
 
-target=$(shell gcc -dumpmachine)
+target=$(shell clang -dumpmachine $(CFLAGS))
 
 target_list=$(filter-out gnu,$(subst -, ,$(target)))
 target_cpu=$(word 1,$(target_list))
@@ -188,6 +188,9 @@ else
   target_os=$(word 3,$(target_list))
 endif
 
+$(info Target OS - $(target_os))
+$(info Target CPU - $(target_cpu))
+
 RTS=$(pwd)/lib/rts-native
 RTSDIR=$(RTS)/adainclude
 RTSLIB=$(RTS)/adalib
-- 
2.45.2
```
2. GNAT LLVM project itself needs a copy of libgnat to build successfully. So for a cross-compilation toolchain it is necessary to build it twice (once for host and once for target). AFAIR I bypassed this by applying this patch and the then "next" one after building the toolchain without it using `make gnatlib CFLAGS="-O2 --target=aarch64-linux-android29"`. A better fix is certainly needed. "Next" patch is 
```patch
From 8b6f3532a9919acea4a3602f6752029997d98d7a Mon Sep 17 00:00:00 2001
From: anonymix007 <48598263+anonymix007@users.noreply.github.com>
Date: Mon, 25 Mar 2024 23:06:39 +0300
Subject: [PATCH 2/4] Add gnat_src to include paths

---
 llvm-interface/Makefile | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/llvm-interface/Makefile b/llvm-interface/Makefile
index 5d9f6d6c..7877c0d9 100644
--- a/llvm-interface/Makefile
+++ b/llvm-interface/Makefile
@@ -212,7 +212,7 @@ include $(GNAT_SRC)/Makefile.rtl
 
 gnatlib: build
 	$(RMDIR) $(RTS)
-	$(MAKE) CFLAGS="$(CFLAGS)" EXTRALIBFLAGS="$(EXTRALIBFLAGS)" quicklib
+	$(MAKE) CFLAGS="$(CFLAGS) -I$(GNAT_SRC)" EXTRALIBFLAGS="$(EXTRALIBFLAGS)" quicklib
 
 gnatlib-automated: build-opt
 	$(RMDIR) $(RTS)
-- 
2.45.2
```

**Comment by ArnaudCharlet** [comment]
Thanks for the suggestions. For patch 1, I assume you meant to send only the first hunk, the second hunk is debug code that we don't want to integrate. Depending from where you start, GCC or clang might be correct, so it's unclear that your change is going in the right direction, and another change may be needed such as introducing an intermediate TARGET_CC make variable and call $(TARGET_CC) -dumpmachine $(CFLAGS) and have a default setting of TARGET_CC which I would keep at "gcc" and you could override it when building via e.g. make TARGET_CC=clang.

For patch 2, I do not understand it, GNAT_SRC shouldn't be needed here, so there's probably something else to change in your build setup (such as adding the appropriate --target compiler switch. Note also that to build GNAT LLVM, you need an existing GNAT. If you want to build GNAT LLVM with GNAT LLVM (which isn't recommended) then you indeed need to perform two separate builds: a first GNAT LLVM native build, and then a "cross" GNAT LLVM build.

**Comment by anonymix007** [comment]
The thing is, currently multi-target cross-toolchain doesn't seem to be possible. This is the actual problem, most of the other reported issues are just symptoms of that.

Host GCC is not able to build anything for target because it's for `x86_64-pc-linux-gnu` (at least in my distro, though I'd assume it's the same for most of them). I already forgot all the details, so not sure why these changes were necessary, maybe there is a simpler way to achieve all of that.

This all is very confusing though, basically there are 3 (potentially different) architectures here:

1. Host: machine on which GNAT LLVM is currently built
2. Build: machine on which it is intended to be used 
3. Target: machine which will be running code build with GNAT LLVM

Consider that one needs GNAT LLVM for Android (basically, Android NDK with Ada).
For that it'll most likely be:
1. Host: x86_64
2. Build:  x86_64
3. Target: {aarch64,arm}-android

Official NDK has separate directories for each target:
```
toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/
├── aarch64-linux-android
├── arm-linux-androideabi
├── i686-linux-android
├── riscv64-linux-android
└── x86_64-linux-android
```
IMHO GNAT LLVM needs to be restructured to do something similar, that way it would be much clearer what exactly is wrong. 

Another issue is that GNAT itself is definitely broken for some of these targets (i.e. `aarch64-linux-android`) and that was reported previously at https://github.com/AdaCore/gnat-llvm/issues/39#issuecomment-2022432338 
Not sure how we would proceed with this though.

**Comment by ArnaudCharlet** [comment]
Indeed, and we have no plans at this stage to implement that in GNAT LLVM, so it's probably better to close this issue for the time being and revisit in the future if some suitable solution to tackle the core need is found/proposed. As for GNAT being broken, this is out of scope for this repository and would need to be brought to gcc.gnu.org directly. I'll reiterate the recommendation I made under #39: you'll get more chances of progress and success if you don't mix all your items under a single issue, and split them one by one, without mixing the discussions, and opened on the relevant projects.
