### ISSUE TITLE
gnat-llvm build failure (25.1)

### ISSUE THREAD

**Issue by nerdtype** [AdaCore/gnat-llvm#48]
The 'make llvm' command is successful, but the 'make' command failed.  I have attached a snip of the last part of the build failure.

System Configuration:
- Linux 6.9.3
- clang 16.0.6 (https://github.com/AdaCore/gnat-llvm.git fbd6a428d80d23f9bb1a764e535b27fa20ddd049)
- llvm-config 16.0.6
- gnatmake 14.2.0
- gnat 14.2.0

Error:

`> make`

[8< SNIP 8<]

  gnat1: warning: command-line option '-Wno-implicit-function-declaration' is valid for C/ObjC but not for 
  gnat1: warning: command-line option '-Wno-implicit-function-declaration' is valid for C/ObjC but not for 
  /home/N/.alire/bin/gcc -c -x ada -gnatA -O2 -g -Wno-implicit-function-declaration -I/home/N/Desktop/gnat-
  gnat1: warning: command-line option '-Wno-implicit-function-declaration' is valid for C/ObjC but not for 
  /home/N/.alire/bin/gcc -c -x ada -gnatA -O2 -g -Wno-implicit-function-declaration -I/home/N/Desktop/gnat-
  gnat1: warning: command-line option '-Wno-implicit-function-declaration' is valid for C/ObjC but not for 
  /home/N/.alire/bin/gcc -c -x ada -gnatA -O2 -g -Wno-implicit-function-declaration -I/home/N/Desktop/gnat-
  /home/N/.alire/bin/gcc -c -x ada -gnatA -O2 -g -Wno-implicit-function-declaration -I/home/N/Desktop/gnat-
  gnat1: warning: command-line option '-Wno-implicit-function-declaration' is valid for C/ObjC but not for 
  gnat1: warning: command-line option '-Wno-implicit-function-declaration' is valid for C/ObjC but not for 
  /home/N/.alire/bin/gcc -c -x ada -gnatA -O2 -g -Wno-implicit-function-declaration -I/home/N/Desktop/gnat-
  gnat1: warning: command-line option '-Wno-implicit-function-declaration' is valid for C/ObjC but not for 
  /home/N/.alire/bin/gcc -c -x ada -gnatA -O2 -g -Wno-implicit-function-declaration -I/home/N/Desktop/gnat-
  /home/N/.alire/bin/gcc -c -x ada -gnatA -O2 -g -Wno-implicit-function-declaration -I/home/N/Desktop/gnat-
  gnat1: warning: command-line option '-Wno-implicit-function-declaration' is valid for C/ObjC but not for 
  gnat1: warning: command-line option '-Wno-implicit-function-declaration' is valid for C/ObjC but not for 
  /home/N/.alire/bin/gcc -c -x ada -gnatA -O2 -g -Wno-implicit-function-declaration -I/home/N/Desktop/gnat-
  gnat1: warning: command-line option '-Wno-implicit-function-declaration' is valid for C/ObjC but not for 
  a-rttiev.adb:58:04: error: instantiation error at a-iteint.ads:32   
  a-rttiev.adb:58:04: error: instantiation error at a-cdlili.ads:77   
  a-rttiev.adb:58:04: error: run-time library configuration error   
  a-rttiev.adb:58:04: error: file s-finmas.ads not found   
  a-rttiev.adb:58:04: error: entity "System.Finalization_Masters.Finalization_Master_Ptr" not available    
  compilation abandoned   
     
     compilation of a-rttiev.adb failed   
     
  gprbuild: *** compilation phase failed   
  make[2]: *** [Makefile:259: quicklib] Error 4   
  make[2]: Leaving directory '/home/N/Desktop/gnat-llvm/llvm-interface'       
  make[1]: *** [Makefile:227: gnatlib-automated] Error 2   
  make[1]: Leaving directory '/home/N/Desktop/gnat-llvm/llvm-interface'       
  make: *** [Makefile:2: all] Error 2

**Comment by ArnaudCharlet** [comment]
This error typically means that there is a mismatch between the GNAT sources from GCC and the GNAT LLVM sources.
