### ISSUE TITLE
msys2/mingw64 build failure (a-except.adb)

### ISSUE THREAD

**Issue by Alex-Gamper** [AdaCore/gnat-llvm#7]
Hi AdaCore

The latest build of the Ada runtime has now regressed with the latest git version
under msys2/mingw64. Below is the error that I am seeing. I got around it by setting the
optimization to -O0 for a-except in makefile.rtl. Not sure if this is an optimal solution, But I thought
it relevant to bring to your attention.  Notice that the last -O1 I think overrides any previous
setting ?

Thanks Alex

/home/alexg/Software/gnat-llvm/llvm-interface/bin/llvm-gcc -c -O0 -g -gnatpg -nostdinc -I../adainclude  -g \
  -fno-inline -fno-toplevel-reorder -O0 -O1 -nostdinc -I../adainclude \
  ../adainclude/a-except.adb -o a-except.o
a-except.adb:701:09: warning: optimization breaks taking addresses of labels
a-except.adb:1771:09: warning: optimization breaks taking addresses of labels
make[3]: *** [/home/alexg/Software/gnat-llvm/llvm-interface/gnat_src/Makefile.rtl:2736: a-except.o] Error 1
make[3]: Leaving directory '/home/alexg/Software/gnat-llvm/llvm-interface/lib/rts-native/adalib'
make[2]: *** [Makefile:227: quicklib] Error 2
make[2]: Leaving directory '/home/alexg/Software/gnat-llvm/llvm-interface'
make[1]: *** [Makefile:203: gnatlib-automated] Error 2
make[1]: Leaving directory '/home/alexg/Software/gnat-llvm/llvm-interface'
make: *** [Makefile:2: all] Error 2

**Comment by ArnaudCharlet** [comment]
You need to to an svn update on llvm-interface/gnat_src.
In general every time you update GNAT LLVM sources you should also also the gnat_src directory since sometimes synchronized changes are done in both repositories.

**Comment by Alex-Gamper** [comment]
Understood, and gnat-llvm now builds cleanly, thanks for your great effort !

Alex

**Comment by ArnaudCharlet** [comment]
Great, thanks for confirming.
