### ISSUE TITLE
Typo fixes

### ISSUE THREAD

**Issue by okellogg** [AdaCore/gnat-llvm#8]
While looking at the code, I noticed a few typos which I fixed in the attached patch.
Hope this helps.

[gnat-llvm-master-10afc23-typo-fixes.diff.gz](https://github.com/AdaCore/gnat-llvm/files/4080849/gnat-llvm-master-10afc23-typo-fixes.diff.gz)

**Comment by ArnaudCharlet** [comment]
Thanks Oliver for your contribution, we'll integrate it!

**Comment by ArnaudCharlet** [comment]
Done, thanks again for your contribution.
